# Do not change the values in these files.

set(OPENCMISS_ZINC_SOURCE_DIR @OPENCMISS_ZINC_ROOT@/src)
set(OPENCMISS_ZINC_BINARY_MPI_DIR @OPENCMISS_ZINC_ROOT@/build${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_ZINC_BINARY_NO_MPI_DIR @OPENCMISS_ZINC_ROOT@/build${ARCHITECTURE_NO_MPI_PATH})
set(OPENCMISS_ZINC_INSTALL_MPI_PREFIX @OPENCMISS_ZINC_ROOT@/install${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_ZINC_INSTALL_NO_MPI_PREFIX @OPENCMISS_ZINC_ROOT@/install${ARCHITECTURE_NO_MPI_PATH})

set(OPENCMISS_IRON_SOURCE_DIR @OPENCMISS_IRON_ROOT@/src)
set(OPENCMISS_IRON_BINARY_MPI_DIR @OPENCMISS_IRON_ROOT@/build${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_IRON_BINARY_NO_MPI_DIR @OPENCMISS_IRON_ROOT@/build${ARCHITECTURE_NO_MPI_PATH})
set(OPENCMISS_IRON_INSTALL_MPI_PREFIX @OPENCMISS_IRON_ROOT@/install${ARCHITECTURE_MPI_PATH})
set(OPENCMISS_IRON_INSTALL_NO_MPI_PREFIX @OPENCMISS_IRON_ROOT@/install${ARCHITECTURE_NO_MPI_PATH})
